prerelease: false
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: |
  ### $TITLE [PR #$NUMBER]
no-changes-template: 'No changes'
change-title-escapes: '\<*_&'
template: |
  ## What's Changed

  $CHANGES
  {{ SQUASHED_EXTENDED_DESCRIPTION }}

  ###### Previous Tag: $PREVIOUS_TAG
autolabeler:
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
      - '/enhancement\/.+/'
  - label: 'bug'
    branch:
      - '/bug\/.+/'
      - '/fix\/.+/'
      - '/bugfix\/.+/'
      - '/hotfix\/.+/'
      - '/patch\/.+/'
      - '/issue\/.+/'
    title:
      - '/fix/i'
  - label: 'documentation'
    branch:
      - '/docs\/.+/'
      - '/doc\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
exclude-labels:
  - 'chore'
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
      - 'hotfix'
      - 'patch'
      - 'issue'
      - 'documentation'
      - 'docs'
      - 'doc'
  default: minor
