name: "Releaser"


on:
  pull_request:
    types: [closed]
    branches:
      - 'main'


jobs:

  update_documentation:
    name: "Doc Updater"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Update Action documentation"
        id: actions-docs
        uses: npalm/action-docs-action@v1.1.0
      - name: "Commit-back changes"
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            README.md
          commit-message: "update README"
          ref: ${{ github.head_ref }}

  release:
    name: "Releaser"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - id: releaser
        uses: release-drafter/release-drafter@v5.15.0
        with:
          config-name: releaser_config.yml
          disable-autolabeler: true
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Trigger the Notifier"
        if: success()
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.CI_GH_PAT_REPO_DISPATCH_API_AUTH }}
          event-type: slack-notification
          client-payload: '{ "type": "build", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "color": "#2EB67D", "title": "${{ github.repository }} New Release", "message": "🚀  Check-out ${{ steps.releaser.outputs.html_url }}" }'
